### ISSUE TITLE
求助：关于hexo主题博客

### ISSUE THREAD

**Issue by rickyyangrui** [AlynxZhou/stackharbor.alynx.xyz#1]
博主你好啊，我比较的喜欢你的主题，你用的事next -》 Pisces 的主题，我用的也是，我现在想变成你的这个样式，应该怎么办呢？我如何可以直接套用你的theme类？哈哈哈，直接下载你这里的代码吗？

**Comment by AlynxZhou** [comment]
@rickyyangrui 你去next的仓库，按照它的README去安装设置就好了，下载这里没用的，这里是生成的网页。
